### ISSUE TITLE
TESTS!

### ISSUE THREAD

**Issue by Oliversw** [FAC-Sixteen/spellchecker#31]
YOU HAVE THEM!

AND THEY'RE PASSING!

💯 

I think you implemented them in a really DRY and effective way too. Very impressed.

**Comment by charlielafosse** [comment]
![](https://media.giphy.com/media/3owypjhoPF0F2J2T1C/giphy.gif)

**Comment by starsuit** [comment]
![boom](https://media.giphy.com/media/3PEnJiyzIAVi/giphy.gif)
