### ISSUE TITLE
Spell lingers 

### ISSUE THREAD

**Issue by sylv1ah** [FAC-Sixteen/spellchecker#36]
Not sure if it was intentional but the spell that was last clicked stays there even when the input field is cleared
<img width="818" alt="Screenshot 2019-03-29 at 10 43 29" src="https://user-images.githubusercontent.com/35779506/55227619-d8651100-520f-11e9-9d1e-bf1a5e5ab3c8.png">
Maybe you could clear the ul element containing them when the user clicks a new key?

**Comment by sylv1ah** [comment]
oops this issue is the same as issue #25

**Comment by bobbysebolao** [comment]
Thanks for the feedback, we've fixed this now!
