### ISSUE TITLE
Congrats everyone!!

### ISSUE THREAD

**Issue by Oliversw** [FAC-Sixteen/spellchecker#37]
I'm really impressed overall! Your project is clean and well thought through. There are tests, BEM, and a lot of great ideas! Much cleaner than projects we managed to do in our time 😉 

![](https://media.giphy.com/media/hiKKdda4mdn8Y/giphy.gif)

**Comment by Oliversw** [comment]
AND Heroku!

**Comment by starsuit** [comment]
👍
