### ISSUE TITLE
event.which vs event.key

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/spellchecker#46]
https://github.com/FAC-Sixteen/spellchecker/blob/8f83db49a97edd749d1ef12932566e275c6f5f6e/public/script.js#L67

`event.which` is an old deprecated property. You'll probably find it easier to use `event.key`. This actually gives you a string representation of the character rather than a keyCode (e.g. `"ArrowDown", "Enter", "Escape" etc)

**Comment by oliverjam** [comment]
Just an FYI: it's generally a good idea to keep issues open until you've actually pushed the code that fixes them, to keep track.

You can associate PRs/commits with an issue by putting e.g. "relates #46" in the body to get it to show up here

**Comment by starsuit** [comment]
><
